image: simgrid/unstable

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    # Install the deps
    - apt-get update
    - apt-get install -y cmake build-essential libboost-dev libboost-all-dev git
    # Build S4BXI
    - ./rebuild.sh
    - export PATH=$PATH:/opt/s4bxi/bin:/usr/lib/x86_64-linux-gnu/simgrid
    - export LD_LIBRARY_PATH=/opt/s4bxi/lib:/usr/lib/x86_64-linux-gnu
    # Run tests
    - cd teshsuite && ./run.sh
